In [1]:
import numpy as np


In [5]:
def calcular_norma(matriz):
    # Se generan los test cases con vectores canónicos
    test_cases = [[1 if i == j else 0 for j in range(len(matriz))] for i in range(len(matriz))]

    valores_p = [1,2,3,np.inf]
    for p in valores_p:
        dimension = len(matriz)

        # Generar un vector aleatorio con valores en una distribución normal estándar

        for i in range(10000):
            vector_aleatorio = np.random.randn(dimension)

            # Calcular la norma euclidiana del vector
            norma = np.linalg.norm(vector_aleatorio, ord = p)

            # Normalizar el vector dividiendo por su norma
            vector_normalizado = vector_aleatorio / norma
            test_cases.append(vector_normalizado)

        max = 0

        for vec in test_cases:
            producto = np.dot(matriz,vec)
            resultado = np.linalg.norm(producto, ord = p)

            if (max < resultado):
                max = resultado

        print("Norma Orden ",p,": ",max)


In [6]:
for i in range(2,11):
    n = i  # Tamaño de la matriz (ixi de 2 hasta 10)

    matriz_hilbert = np.zeros((n, n))

    for i in range(1, n + 1):
        for j in range(1, n + 1):
            matriz_hilbert[i - 1, j - 1] = 1 / (i + j - 1)
    
    print("MATRIZ HILBERT ",i,"x",i)
    print(matriz_hilbert)
    calcular_norma(matriz_hilbert)
    print("------------")


MATRIZ HILBERT  2
[[1.         0.5       ]
 [0.5        0.33333333]]
Norma Orden  1 :  1.5
Norma Orden  2 :  1.267591862579397
Norma Orden  3 :  1.2860141962484994
Norma Orden  inf :  1.4997775922302454
------------
MATRIZ HILBERT  3
[[1.         0.5        0.33333333]
 [0.5        0.33333333 0.25      ]
 [0.33333333 0.25       0.2       ]]
Norma Orden  1 :  1.8333333333333333
Norma Orden  2 :  1.4082202693614025
Norma Orden  3 :  1.4402850884472298
Norma Orden  inf :  1.8159524642473455
------------
MATRIZ HILBERT  4
[[1.         0.5        0.33333333 0.25      ]
 [0.5        0.33333333 0.25       0.2       ]
 [0.33333333 0.25       0.2        0.16666667]
 [0.25       0.2        0.16666667 0.14285714]]
Norma Orden  1 :  2.083333333333333
Norma Orden  2 :  1.4986905197292946
Norma Orden  3 :  1.5400059045662924
Norma Orden  inf :  1.9575737079359596
------------
MATRIZ HILBERT  5
[[1.         0.5        0.33333333 0.25       0.2       ]
 [0.5        0.33333333 0.25       0.2        0.1

In [4]:
import numpy as np

n = 10  # Tamaño de la matriz de Hilbert (10x10 en este caso)

# Función para calcular la norma infinito de una matriz
def calcular_norma_infinito(matriz):
    maximo_valor_absoluto = np.max(np.sum(np.abs(matriz), axis=1))
    return maximo_valor_absoluto

# Genera una matriz de Hilbert 10x10
matriz_hilbert = np.zeros((n, n))
for i in range(1, n + 1):
    for j in range(1, n + 1):
        matriz_hilbert[i - 1, j - 1] = 1 / (i + j - 1)

# Calcula la norma infinito de la matriz de Hilbert
norma_infinito = calcular_norma_infinito(matriz_hilbert)

print("Norma infinito de la matriz de Hilbert 10x10:", norma_infinito)

Norma infinito de la matriz de Hilbert 10x10: 2.9289682539682538
